
spring:
  application:
    name: zipkin

  # \u89E3\u51B3Zipkin\u542F\u52A8The bean 'characterEncodingFilter', defined in
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9004

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

management:
  metrics:
    web:
      # \u89E3\u51B3Zipkin\u62A5\u9519IllegalArgumentException: Prometheus requires that all meters
      server:
        auto-time-requests: false