
server:
  port: 9003

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8080/eureka/

zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    # 路由名称，随意
    template-admin:
      # 路由地址
      path: /api/admin/**
      # 该路由地址对应的服务名称
      serviceId: admin
    template-auth:
      path: /api/auth/**
      serviceId: auth